model_name: 'AEflow'
cfg_name: 'default'

arch_params:

  hidden_channels: 4
  latent_channels: 8
  kernel_size: 5
  padding_type: ['circular', replicate]
  nresblocks: 4

training_params:

  lr_ed: 3e-4
  nepochs: 10000
  bs: 128
  loss_fn: weighted

