model_name: 'CAE'
cfg_name: 'default'

latent_dim: 1024

arch_params:

  hidden_channels: 32
  latent_channels: 8
  kernel_size: 5
  padding_type: ['circular', 'replicate']
  depth: 3

training_params:

  bs: 128

  lr_ed: 1e-3

  loss_fn_tr: weighted
  loss_fn_va: weighted
