defaults:

  - pretrain_schema
  - dataset: sw
  - encoder_decoder: default_ed
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

seed: 2357
num_gpus: 0

phase: pretrain

name: ${dataset.name}_${encoder_decoder.name}
ckpt_path: ../ckpts/${phase}/${name}.pt

# logging
hydra:
  run:
    dir: outputs/${phase}/${encoder_decoder.model_name}-${encoder_decoder.cfg_name}/${now:%Y%m%d-%H%M%S}

  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log

encoder_decoder:
  name: ${encoder_decoder.model_name}_${encoder_decoder.cfg_name}
