model_name: 'AEflow'
cfg_name: 'default'

latent_dim: 1024

arch_params:

  hidden_channels: 4
  latent_channels: 8
  kernel_size: 5
  padding_type: ['circular', 'replicate']
  nresblocks: 4

training_params:

  lr_ed: 1e-3
  bs: 128
  loss_fn_tr: weighted
  loss_fn_va: weighted

