defaults:

  - default_fouriernetcartes
  - _self_

cfg_name: '1024d'

latent_dim: 1024

arch_params:

  code_dim: 512 # latent dim = [code_dim=200] x [state_channels=2]
  # hidden_dim: 256

training_params:

  bs: 4
  lr_ed: 5e-3