defaults:

  - assimilate_schema
  - dataset: sw
  - encoder_decoder: default_ed
  - latent_dynamics: default_ld
  - uncertainty_est: default_ue
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

name: ${dataset.name}_${encoder_decoder.name}_${latent_dynamics.name}_${uncertainty_est.name}
finetune_name: ${dataset.name}_${encoder_decoder.name}_${latent_dynamics.name}
postproc_name: ${dataset.name}_${encoder_decoder.name}_${latent_dynamics.name}_${uncertainty_est.name}

finetune_ckpt_path: ../ckpts/finetune/${finetune_name}.pt
postproc_ckpt_path: ../ckpts/postproc/${postproc_name}.pt

# logging
hydra:
  run:
    dir: outputs/assimilate/${encoder_decoder.model_name}-${encoder_decoder.cfg_name}/${now:%Y%m%d-%H%M%S}

  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log

encoder_decoder:
  name: ${encoder_decoder.model_name}_${encoder_decoder.cfg_name}

latent_dynamics:
  name: ${latent_dynamics.model_name}_${latent_dynamics.cfg_name}

uncertainty_est:
  name: ${uncertainty_est.model_name}_${uncertainty_est.cfg_name}


seed: 2357
cuda_id: 0
ass_nsteps: 200

sigma_x_b: 1e-1

sigma_o: 1e-1

n_obs: 1024

ens_num: 32
infl: 1.05

save_dir: 'results/'